[workspace]
members = ['waketimed_core', 'waketimed']

[profile.release]
# optimize binary size
# TODO: re-enable strip + opt-level when Debian testing compiler supports them
# strip = true
lto = true
# opt-level = "z"
codegen-units = 1
